### ISSUE TITLE
[Perhaps just a configuration question] Cooperation with osc

### ISSUE THREAD

**Issue by mcepl** [airblade/vim-rooter#102]
For development on Open Build Service (OBS) (used for development of the openSUSE Linux distribution) we use specific custom versioning system (which I hate, but that's besides the point here), which leaves in the root of every project directory ``.osc/``. So, of course I have ``let g:rooter_patterns+=['.osc/']`` in my ``~/.vim/vimrc``.

However, that is not perfect solution. Substantial part of my work on the projects we need to work with expanded tarballs and modifying patches for the individual packages. We use [quilt](http://savannah.nongnu.org/projects/quilt) for that. When I expand the tarball with quilt I get subdirectory with the name of the tarball, which has always subdirectory ``patches/``.

So, for example. There is a directory ``Factory/python/`` which has a subdirectory ``.osc/`` (i.e., ``Factory/python/.osc/``) and the expanded tarball is in ``Factory/python/Python-2.7.17/`` and there is always subdirectory ``patches/`` in it (i.e., ``Factory/python/Python-2.7.17/patches/``). Obviously, the root of this expanded tarball should be in ``Factory/python/Python-2.7.17/``.

I guess, something like ``let g:rooter_patterns+=['.osc/../*/patches/', '.osc/']`` is not possible, right? Would it be possible to delegate the decision to some custom-made function, where I could apply this more complicated logic? How to hook up ``vim-rooter`` with some custom function (kind of reverse of what `FindRootDirectory()`)?

**Comment by airblade** [comment]
I would think this should work: `let g:rooter_patterns=['patches/', '.osc/']` – unless you have `patches/` directories elsewhere that shouldn't trigger vim-rooter.

Also, if you're setting `g:rooter_patterns` in your vimrc, you'll need `=` not `+=` but I'm sure that's a typo; Vim would complain if you actually did that.

**Comment by mcepl** [comment]
> I would think this should work: `let g:rooter_patterns=['patches/', '.osc/']` – unless you have `patches/` directories elsewhere that shouldn't trigger vim-rooter.

That’s actually a great idea, thank you. So simple!

> Also, if you're setting `g:rooter_patterns` in your vimrc, you'll need `=` not `+=` but I'm sure that's a typo; Vim would complain if you actually did that.

Yes, I have found out. What I wrote here was just lovely dream, which didn’t materialize unfortunately.

**Comment by mcepl** [comment]
```
python@stitny$ ls -ld Python-2.7.17/patches
lrwxrwxrwx 1 matej users 2 Feb  8 23:16 Python-2.7.17/patches -> ..
python@stitny$ ls -ld .osc
drwxr-xr-x 2 matej users 4096 Feb  8 23:30 .osc
python@stitny$ grep rooter ~/.vim/vimrc
" for vim-rooter
let g:rooter_change_directory_for_non_project_files = 'current'
let g:rooter_patterns=['.git', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'patches', '.osc/']
let g:rooter_use_lcd = 1
let g:rooter_resolve_links = 0
let g:rooter_silent_chdir = 1
python@stitny$ vim Python-2.7.17/Lib/opcode.py 
python@stitny$
```

When I open vim (actually neovim) with the above mentioned command, I get ``:pwd`` giving me ``/home/matej/build/devel:languages:python:Factory/python``, not expected ``/home/matej/build/devel:languages:python:Factory/python/Python-2.7.17``.

**Comment by airblade** [comment]
Does the  root `Factory/python/` directory contain any of `.git`, `.git/`, `_darcs/`, `.hg/`, `.bzr/`, or `.svn/`?  vim-rooter does a depth-first (height-first?) search over the patterns, not a breadth-first search.

It should be `patches/`.

Is this saying the `patches/` directory is a symlink?  `Python-2.7.17/patches -> ..`

**Comment by mcepl** [comment]
> Does the root `Factory/python/` directory contain any of `.git`, `.git/`, `_darcs/`, `.hg/`, `.bzr/`, or `.svn/`? vim-rooter does a depth-first (height-first?) search over the patterns, not a breadth-first search.

It contains .osc/ directory, nothing else.

> It should be `patches/`.

Even when it is a symlink?

> Is this saying the `patches/` directory is a symlink? `Python-2.7.17/patches -> ..`

Yes.

**Comment by airblade** [comment]
As per https://github.com/airblade/vim-rooter/issues/98#issuecomment-495164169, I think vim-rooter is correctly finding the `patches` symlink; but when Vim looks for the parent of `patches`, it actually looks for the parent of the directory `patches` links to.

There isn't much we can do about this without making the plugin a lot more complicated.

**Comment by mcepl** [comment]
> As per [#98 (comment)](https://github.com/airblade/vim-rooter/issues/98#issuecomment-495164169), I think vim-rooter is correctly finding the `patches` symlink; but when Vim looks for the parent of `patches`, it actually looks for the parent of the directory `patches` links to.

But, I have ``let g:rooter_resolve_links = 0`` so it shouldn’t resolve the symlink, should it?

**Comment by airblade** [comment]
That option applies to the file you are opening, not the rooter pattern(s).  If a rooter pattern is a link, Vim automatically resolves it.

Here's an example.

```
$ mkdir -p p/q
$ mkdir -p a/b
$ touch p/q/foo
$ ln -nfs p/q a/b/c
$ tree
.
├── a/
│   └── b/
│       └── c -> ../../p/q/
├── p/
│   └── q/
│       └── foo
$ vim
:echo fnamemodify('a/b/c/', ':p')
" p/q  (not a/b/c)
```

Vim-rooter finds `patches/` on the file system as expected but reads it as `..` i.e. `Python-2`.  It's not possible to stop vim resolving the link.

**Comment by mcepl** [comment]
> It's not possible to stop vim resolving the link.

Well, it is all in https://github.com/airblade/vim-rooter/blob/8a0a201a17fae3f7656b99f74d67741986faba37/plugin/rooter.vim#L104 , isn’t it?

Couldn’t this function be modified, so it would check whether one ``patterns`` is a symlink and behave better?

**Comment by airblade** [comment]
I have just changed vim-rooter's implementation (9b1fc7a) so it supports globs and breadth-first search.  Please could you update and let me know whether it solves your problem?

**Comment by mcepl** [comment]
Wow! It seems like working with this configuration:
```vim
" for vim-rooter
" Change to file's directory (similar to autochdir).
let g:rooter_change_directory_for_non_project_files = 'current'
let g:rooter_patterns += ['patches', '.osc/']
let g:rooter_use_lcd = 1
let g:rooter_resolve_links = 0
let g:rooter_silent_chdir = 1
```

Actually. Not exactly. The directory layout is thus:
```
python-bidict@stitny$ tree -d -A .
.
└── bidict-0.19.0
    ├── assets
    ├── bidict
    ├── bidict.egg-info
    ├── docs
    │   └── _static
    └── tests
        └── properties
```
When I ``cd bidict-0.19.0`` and just open vim, then ``:pwd`` gives me ``/home/matej/build/devel:languages:python/python-bidict/bidict-0.19.0``, which is correct. But when I start in that directory ``vim README.rst``, then ``pwd`` gives me ``/home/matej/build/devel:languages:python/python-bidict/bidict-0.19.0``, which is obviously wrong.

**Comment by mcepl** [comment]
OK, now, I am confused. It seems to work now. Let me play with it a little bit more, and I will reopen eventually.
