### ISSUE TITLE
Doesn't change to .git - home directory when opening file from vim-startify.

### ISSUE THREAD

**Issue by collegeimprovements** [airblade/vim-rooter#107]
Hi airblade, 

`vim-rooter` works great for me.
It doesn't work though when i open files from `vim-startify` plugin.
Running :Rooter sets the correct working directory (i.e. the directory with .git folder).

**Comment by airblade** [comment]
Try `:let g:startify_change_to_dir = 0`.

https://github.com/mhinz/vim-startify/blob/593388d3dbe7bfdcc06a714550d3253442b2fc65/doc/startify.txt#L364-L370

**Comment by collegeimprovements** [comment]
It works. Thanks a lot @airblade

**Comment by collegeimprovements** [comment]
Hi @airblade `let g:startify_change_to_dir = 0` changes to Root directory (one with `.git` folder in hierarchy) only after saving the file that gets opened. 
Is there a way to change to change to root directory when we open the file from startify and don't save it one time ?

**Comment by airblade** [comment]
I can't reproduce this.  As soon as I open a file from Startify, vim-rooter changes the working directory to the file's root.

**Comment by collegeimprovements** [comment]
Here is a asciinema link of the issue: https://asciinema.org/a/NZo0jp08Dau6Rvd7yGJcuB5ub

**Comment by airblade** [comment]
Thanks for the screencast.  I see the problem but I can't reproduce it.

Please could you share your vimrc / init.vim?

**Comment by collegeimprovements** [comment]
Thanks @airblade .

Nvim Config: https://github.com/collegeimprovements/dotfiles/tree/master/.config/nvim  
Vim-rooter Config: https://github.com/collegeimprovements/dotfiles/blob/master/.config/nvim/plug-config/vim-rooter.vim

Most of the settings: https://github.com/collegeimprovements/dotfiles/blob/master/.config/nvim/general/settings.vim

**Comment by airblade** [comment]
I re-implemented vim-rooter in 9b1fc7a.  Please could you update and let me know whether you still have this problem?

**Comment by collegeimprovements** [comment]
Hi @airblade I still face the same issue with latest version of vim-rooter.
On first save it changes to correct directory(the one with .git folder).

**Comment by airblade** [comment]
I presume you really have set this to 0?

```viml
    let g:startify_change_to_dir = 1
```

https://github.com/collegeimprovements/dotfiles/blob/4991ff3902fa4569fbc0da58575cabf62cd841e5/.config/nvim/plug-config/vim-startify.vim#L1

**Comment by airblade** [comment]
You're sourcing your startify config (with `let g:startify_change_to_dir = 1`) after you source your rooter config (`let g:startify_change_to_dir = 0`) so your rooter config is being overwritten.

```viml
source $HOME/.config/nvim/plug-config/vim-rooter.vim
source $HOME/.config/nvim/plug-config/vim-signify.vim
source $HOME/.config/nvim/plug-config/vim-startify.vim
```

https://github.com/collegeimprovements/dotfiles/blob/4991ff3902fa4569fbc0da58575cabf62cd841e5/.config/nvim/init.vim#L38-L40

**Comment by collegeimprovements** [comment]
Oh. That indeed sorted it. Thanks a lot @airblade 😊
