### ISSUE TITLE
Favor current directory

### ISSUE THREAD

**Issue by cbows** [airblade/vim-rooter#108]
I have the following `g:rooter_patterns` set:
```vim
let g:rooter_patterns = [
  \ 'package.json',
  \ 'requirements.txt',
  \ 'pyproject.toml',
  \ '.git',
  \ '.git/'
  \]
```
The idea is to mark a directory as root if it contains files that indicate a package in some language (e.g. `package.json` for javascript) and fall back to the git submodule or git root directory if none were found. This is helpful for monorepos with different languages. However, it doesn't always work, because vim-rooter favors files earlier in the list, even if the current directory contains a file later in the list.

Here is an example:
```
myproject/
  |-- package.json
  |-- subdir_py/
  |    |-- requirements.txt
  |
  |-- subdir_js/
       |-- package.json
```
**Case 1**: If I start vim in `subdir_js/` it makes `subdir_js/` the root, which is correct

**Case 2**: If I start vim in `subdir_py/` it makes `myproject/` the root, which is not what I expect since my `g:rooter_patterns` contain `requirements.txt` as a root marker. I guess you could say vim-rooter now favors list order instead of directory order.

I am wondering if there is a way to change that behaviour so that vim-rooter works in both cases, meaning files in the current directory take precedence over files in ancestor directories?

**Comment by airblade** [comment]
Thanks for the clear explanation.

There are a couple of pull requests which implement this (#93, #103).  I plan to build this functionality into the code but I haven't had a chance to do it yet.

**Comment by cbows** [comment]
Thank you for hinting towards these pull requests. I wasn't aware.

**Comment by airblade** [comment]
In 9b1fc7a I changed vim-rooter to breadth-first search so it now does what you want.

**Comment by dimotsai** [comment]
@airblade Is there a way go back to the original behavior? Because for some large projects, Case 2 is exactly what I expected.

**Comment by airblade** [comment]
@dimotsai Please could you open a new issue with an example of your directory tree?
