### ISSUE TITLE
Can't open $VIMRUNTIME/syntax/vim.vim

### ISSUE THREAD

**Issue by habamax** [airblade/vim-rooter#112]
* OS: win10
* vim: 8.2.1226

It looks like I can't open any syntax file located in `$VIMRUNTIME/syntax/` folder on windows.

I remember I was able to do it but now it just hangs until you press `Ctrl-C`:

![image](https://user-images.githubusercontent.com/234774/88288100-f3f50480-ccfb-11ea-8c5b-78bbacf327d7.png)

If I remove vim-rooter then it works. Also it works with WSL vim.

**Comment by habamax** [comment]
If after `Ctrl-c` when file is loaded I do `:Rooter` it hangs again.

**Comment by habamax** [comment]
I have put a debug print into `s:root` function:

```
  " breadth-first search
  while len(dir) > 1
    echom "inside root" dir
    for pattern in g:rooter_patterns
...
```

and the output is:
![image](https://user-images.githubusercontent.com/234774/88289612-2dc70a80-ccfe-11ea-89d8-ea0f606eb3fb.png)

**Comment by airblade** [comment]
It walks up the tree until it gets to the top.  It detects the top like this:

```
  while len(dir) > 1
```

Which evidently doesn't work on Windows.  I'll fix it.

**Comment by habamax** [comment]
Thx, works now!
