### ISSUE TITLE
Add option to change current working directory manually

### ISSUE THREAD

**Issue by f0s3** [airblade/vim-rooter#114]
I would like to have an option to manually change the cwd. Something like `RooterChangeDir` or whatever you'd like.
I find it useful to be able to set `src` folder in java projects so that fzf looks into that only, and not on the files above it.
I haven't found anything like this in the documentation and thought this is a nice feature to have.
Nice plugin btw, like it a lot :smiley:

**Comment by airblade** [comment]
You can run `:Rooter` to manually change the current working directory.

To toggle between automatic and manual, use `:RooterToggle`.  To make Rooter start in manual mode, add this to your vimrc:

```viml
let g:rooter_manual_only = 1
```

**Comment by f0s3** [comment]
I don't quite understand how these commands may help me change my project root. Could you elaborate more?

**Comment by airblade** [comment]
Hmm, I'm not sure what you're asking.  I thought you were asking how to trigger Rooter to change directory.  But are you actually asking how to specify which directory it changes to?

This will make Rooter treat the `src` folder as a project root directory:

```viml
let g:rooter_patterns = ['=src']
```

**Comment by f0s3** [comment]
Yes, that's what I was asking for. Sorry for writing in such a way that you didn't understand the first time you read it. Thank you for your plugin and your help.

**Comment by airblade** [comment]
> Sorry for writing in such a way that you didn't understand the first time you read it.

No need to apologise :)

I'm glad we found a solution.
