### ISSUE TITLE
Question: How do you call FindRootDirectory

### ISSUE THREAD

**Issue by zlksnk** [airblade/vim-rooter#119]
Hey! I'm new to Vim. I am trying to use `FindRootDirectory` to call and use it for another plug-in.  I'm using NeoVim so my config is in `init.vim` file and I've installed plugins using vim-plug. 

NVim complains that `FindRootDirectory` is not defined (it is telling me that it is an unknown function). How can I call this external (but public) function? I tried functions that are exposed from other plugins and I can confirm that they do work

**Comment by airblade** [comment]
You can check whether vim-rooter is installed correctly with this command (inside NeoVim):

```
:filter rooter scriptnames
```

You'll see a number and a colon and the path to the installation directory if it's installed, and nothing otherwise.

You could call the function like this:

```
:echo FindRootDirectory()
:let dir = FindRootDirectory()
:call FindRootDirectory()
```

The last one isn't useful here because the function doesn't have any side-effects and you lose the return value.

**Comment by zlksnk** [comment]
Thanks for responding back. One thing that I missed to tell last time is that `FindRootDirectory` does work in command but NVim isn't able to find it when I try to call it in `init.vim`. Is there a way to debug and fix that?

**Comment by airblade** [comment]
Ah, that's because NeoVim loads plugins after it has read `init.vim`.  You can read more at `:help startup`.

What are you trying to achieve?  Perhaps I can suggest a way to get there.

**Comment by zlksnk** [comment]
Oh, thank you! There is a plugin named [vim-startify](https://github.com/mhinz/vim-startify) and it exposes [a global variable](https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt#L159) into which I need to call `FindRootDirectory`. (I need to replace [`getcwd`](https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt#L161) with `FindRootDirectory`.)

**Comment by airblade** [comment]
I'm not familiar with vim-startify but I had a quick look.  Unfortunately I can't see an easy way to do it.  I suggest you ask on the Startify repo.

**Comment by zlksnk** [comment]
Calling `FindRootDirectory` from `config/.nvim/after/plugin/<plugin-name>.vim` works.
