### ISSUE TITLE
nerdtree support

### ISSUE THREAD

**Issue by Lazerbeak12345** [airblade/vim-rooter#121]
Hey there!

Could support please be added for [`preservim/nerdtree`](https://github.com/preservim/nerdtree)? It's a more user-friendly vim file explorer that some people use.

This would be so that when a nerdtree instance opens up this will treat it like any other file opened up (but it's a directory, of course).

**Comment by airblade** [comment]
By default vim-rooter runs when you open a directory.  Please could you give me the exact steps to reproduce this problem?  (I wasn't able to reproduce it but I've never used NERDTree so I don't know what to look for.)

**Comment by Lazerbeak12345** [comment]
I’m so sorry that I haven’t been able to get around to this. I had planned upon providing example vimrc files to test this with.

Using a plug-in manager such as plugged only have vim-rooter and the appropriate settings to make it automatically change the cwd when opening a folder.

Run “vim ./a-folder” (assuming that folder exists) and it should do exactly what you described, that is changing cwd to “./a-folder” (note that I haven’t tested this myself)

Install nerdtree. Use the default nerdtree settings. Run the same command to open a directory and you will see that instead of the typical file explorer built-in to vim you will see a different one (this is nerdtree). Vim-rooter currently doesn’t change the cwd when nerdtree is used instead of the built-in file explorer.

I hope this helps and perhaps if I have more time I’ll make the example vimrc files.

**Comment by airblade** [comment]
Thanks for the extra information.

I have updated Rooter to work with NERDTree.  Please also see `:help NERDTreeChDirMode`.

**Comment by Lazerbeak12345** [comment]
Thanks! I'll give this a try!

**Comment by Lazerbeak12345** [comment]
Worked like a charm! I actually didn't even notice it worked till I had used it a few times :smile:

**Comment by piotryordanov** [comment]
Can you tell me how exactly to set it up?

I have in my `.vimrc` the following: `let NERDTreeChDirMode=2`
And yet, changing files in different directory, does not automatically update NERDTree!

**Comment by airblade** [comment]
@piotryordanov Please could you give me the exact steps to reproduce your problem, including what you expect to happen and what actually happens?

**Comment by piotryordanov** [comment]
Hey sorry for the delay.
So actually it turned out that rooter was working as expected, but NERDTree did not do what I expected simply because I was starting vim from `~`

So, problem solved :) Thx for taking the time to answer me!
