### ISSUE TITLE
Reverse range in character class

### ISSUE THREAD

**Issue by staticssleever668** [airblade/vim-rooter#122]
## Description
Sometimes when I open files with some characters in a directory's name in file path, vim-rooter prints an error.
The problem seems to be related to these symbols: `-`, `[`, `]` and character `u`.

## Steps to reproduce 
`folder_name="[u-a]" && mkdir -p "$folder_name" && touch "$folder_name/dummy" && vim "$folder_name/dummy"`
Other folder names that trigger this error: `[Au-S]`, `[Audio-Stuff]`.

## Full error message:
```
Error detected while processing function <SNR>35_rooter[5]..<SNR>35_root[11]..<SNR>35_match[8]..<SNR>35_has:
line    1:
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
E944: Reverse range in character class
Press ENTER or type command to continue
Error detected while processing function <SNR>35_rooter[5]..<SNR>35_root[11]..<SNR>35_match[8]..<SNR>35_has:
line    1:
E944: Reverse range in character class
Press ENTER or type command to continue
Error detected while processing function <SNR>35_rooter[5]..<SNR>35_root[11]..<SNR>35_match[8]..<SNR>35_has:
line    1:
E944: Reverse range in character class
Press ENTER or type command to continue
Error detected while processing function <SNR>35_rooter[5]..<SNR>35_root[11]..<SNR>35_match[8]..<SNR>35_has:
line    1:
E944: Reverse range in character class
Press ENTER or type command to continue
Error detected while processing function <SNR>35_rooter[5]..<SNR>35_root[11]..<SNR>35_match[8]..<SNR>35_has:
line    1:
E944: Reverse range in character class
Press ENTER or type command to continue
Error detected while processing function <SNR>35_rooter[5]..<SNR>35_root[11]..<SNR>35_match[8]..<SNR>35_has:
line    1:
E944: Reverse range in character class
Press ENTER or type command to continue```

**Comment by airblade** [comment]
Thank you for the clear bug report along with steps to reproduce :)

The "Reverse range in character class" error means that Vim is treating the folder name as a regexp; and `[u-a]` looks like a character class except backwards – i.e. if it's a regexp it should be `[a-u]`.

```vim
:echo 's' =~ '[r-t]'     " => 1
:echo 's' =~ '[t-r]'     " => E944: Reverse range in character class
```

Of course the code should be treating the name as a literal, not a regexp.  I'll fix it up.

**Comment by airblade** [comment]
The underlying problem is that when Rooter searches for "has" patterns, which are the most common, it uses [`globpath()`](https://github.com/airblade/vim-rooter/blob/544e701066c69bbeb45297d0285c2719e125440b/plugin/rooter.vim#L169).  This concatenates the directory it's currently testing and the rooter pattern (e.g. `.git`), then expands the result with `glob()`.  `glob()` expands the wildcards `?`, `*`, `**`, and `[abc]` (character classes) – see `:help wildcards`.

I had hoped that only the rooter pattern would be treated as a glob, not the directory too.

So the problem is that even if your rooter patterns don't contain any wildcards, if you use "has" patterns and any of your files' ancestor directories contain wildcards, you'll get this undesired behaviour.

**Comment by airblade** [comment]
Does this patch solve the problem for you?

```diff
diff --git i/plugin/rooter.vim w/plugin/rooter.vim
index 4573cbd..55b6b18 100644
--- i/plugin/rooter.vim
+++ w/plugin/rooter.vim
@@ -166,7 +166,7 @@ endfunction
 " dir        - full path to a directory
 " identifier - a file name or a directory name; may be a glob
 function! s:has(dir, identifier)
-  return !empty(globpath(a:dir, a:identifier, 1))
+  return !empty(globpath(escape(a:dir, '*[]'), a:identifier, 1))
 endfunction

```

**Comment by staticssleever668** [comment]
Yes, it fixes the issue.

**Comment by airblade** [comment]
Thanks for confirming.
