### ISSUE TITLE
Is there a debug mode? vim rooter on mac always navigates up to $HOME

### ISSUE THREAD

**Issue by guysherman** [airblade/vim-rooter#127]
I am on macOS 11.6.4
neovim 0.6.1

When vim opens with an empty buffer (no filename associated) vim rooter seems to change the working directory to $HOME. Oddly this doesn't seem to happen on my linux box running neovim 0.7.

Is there a debug more or some way I can audit why it is doing this?

**Comment by airblade** [comment]
There isn't a debug mode as such.  All I can suggest is adding `echom` statements to the code to find out what is happening.

The first thing to establish is whether or not the plugin thinks the empty buffer is under a root.  Either it thinks it is, and that the root is $HOME; or it thinks it isn't, and that the correct fallback is to change to $HOME.

You could start in the `s:rooter()` function to establish whether a root is found.

If it is, you could figure out why by tracing the `s:root()` function.

If it isn't, you can check the `s:rootless()` function, especially the value of `g:rooter_change_directory_for_non_project_files`.

**Comment by guysherman** [comment]
Thanks for the tips. I finally got round to doing it, and surprise surprise, there was a file in my home directory that was convincing it the home was a valid root, so it was never dropping into rootless mode for unnamed and/or nerd tree buffers.
