### ISSUE TITLE
Rooter does not work for criu/go-criu repositories

### ISSUE THREAD

**Issue by snprajwal** [airblade/vim-rooter#129]
Rooter fails to set cwd as the root dir for both these repositories:
- https://github.com/checkpoint-restore/criu
- https://github.com/checkpoint-restore/go-criu

I am unsure why this is happening, since these are perfectly ordinary git repos, and rooter works for all the other git repos I work with

**Comment by airblade** [comment]
What is your `g:rooter_patterns`?

**Comment by snprajwal** [comment]
@airblade g:rooter_patterns = ['.git', '_darcs', '.hg', '.bzr', '.svn', 'Makefile', 'package.json']

**Comment by snprajwal** [comment]
Is there a way to set a priority for these patterns? I've noticed that the Makefile in the nested dirs is overriding the .git folder in the root dir, that's probably what's causing it to not set the correct cwd

**Comment by airblade** [comment]
Just set the variable in your vimrc, e.g. `let g:rooter_patterns ['.git']`.
