### ISSUE TITLE
buftype guard in s:activate

### ISSUE THREAD

**Issue by tpict** [airblade/vim-rooter#132]
I'm trying out [dirbuf](https://github.com/elihunter173/dirbuf.nvim) but finding that rooter doesn't update the working directory while browsing with it. This is because [this line of the plugin](https://github.com/airblade/vim-rooter/blob/0415be8b5989e56f6c9e382a04906b7f719cfb38/plugin/rooter.vim#L90) exits early unless `buftype` is empty or set to `nofile`, and dirbuf uses `acwrite`.

Would it be possible to add `acwrite` to the list of "allowed" `buftype`s, or to add a configuration option for which types should be ignored?

**Comment by airblade** [comment]
Thanks for the suggestion.

**Comment by airblade** [comment]
@tpict I decided I should invert the logic...sorry if you've already used the previous configuration option.

**Comment by tpict** [comment]
Thanks so much for the quick response! Going on six years of vim-rooter usage :)
