### ISSUE TITLE
Get vim-rooter to detect git worktree

### ISSUE THREAD

**Issue by tmzhuang** [airblade/vim-rooter#133]
Hi there,

I need to work on several branches of the same git repo at once. I have several branches checked out as worktrees in different directory. Unfortunately, it seems vim-rooter will set the cwd to the original checkout of the repo if I start vim in one of these worktree. Is there a way to configure it so that it sets the cwd to the root of the worktree instead?

**Comment by airblade** [comment]
Does adding `!.git/worktrees` to your `g:rooter_patterns` help?

```vim
let g:rooter_patterns=["!.git/worktrees", ".git"]
```

(From #110.)

**Comment by tmzhuang** [comment]
Thanks so much for the quick response (and also the great tool!). Upon further inspection it might be an issue with fugitive. I noticed that during a cherry pick, on conflicts, the git status wasn't showing correctly in the fugitive git window. I thought it was related to rooter setting the wrong project directory but I'll have to look more into it.

**Comment by airblade** [comment]
You could uninstall vim-rooter and see if the problem is still there.  Or vice versa – uninstall fugitive.
