### ISSUE TITLE
User configurable "get file path from buffer" function

### ISSUE THREAD

**Issue by tpict** [airblade/vim-rooter#136]
I was recently trying out https://github.com/stevearc/oil.nvim, but found that it didn't trigger vim-rooter because the buffer name is prefixed with `oil://`.

Would it be possible to add a configuration option for a function that receives a buffer, and returns a file path? It would default to `expand('%')` (or whatever the current behavior is). Then the user could filter out URI protocols etc as needed.

This could also be used to enable things like syncing with the active directory in a Neovim terminal buffer.

Thanks!

**Comment by airblade** [comment]
Are all buffer names prefixed with `oil://` or just buffers holding directory listings?

vim-rooter gets the current path in a few places:

- [when deciding whether to look for a buffer's root](https://github.com/airblade/vim-rooter/blob/1353fa47ee3a81083c284e28ff4f7d92655d7c9e/plugin/rooter.vim#L102)
- [when looking for a buffer's root](https://github.com/airblade/vim-rooter/blob/1353fa47ee3a81083c284e28ff4f7d92655d7c9e/plugin/rooter.vim#L127)
- [when a root wasn't found](https://github.com/airblade/vim-rooter/blob/1353fa47ee3a81083c284e28ff4f7d92655d7c9e/plugin/rooter.vim#L246)

The latter two call [`s:current()`](https://github.com/airblade/vim-rooter/blob/1353fa47ee3a81083c284e28ff4f7d92655d7c9e/plugin/rooter.vim#L216-L223).

Now that I write it out, I'm not sure why the first one doesn't just call `s:current()`.

Are you asking for `s:current()` to be replaceable by a user-supplied function?

**Comment by airblade** [comment]
Ok, and what problem is vim-rooter causing by not triggering on a directory listing?

**Comment by tpict** [comment]
With other plugins that do the same thing (dirvish, dirbuf.nvim), vim-rooter _is_ triggered when navigating directories, which is desirable for me 😄

**Comment by airblade** [comment]
Please can you try out the branch in #137?
