### ISSUE TITLE
why there's a .git and .git/ search pattern?

### ISSUE THREAD

**Issue by albfan** [airblade/vim-rooter#36]
Cannot '.git' pattern be removed?

[plugin/rooter.vim:23](https://github.com/airblade/vim-rooter/blob/master/plugin/rooter.vim#L23)

What is it used for?

**Comment by airblade** [comment]
The `.git` filename is for working with submodules.  See the Note in the Description [here](http://git-scm.com/docs/gitrepository-layout).  You'll find more information if you search this project's issues for 'submodule' (e.g. #22).
