### ISSUE TITLE
Auto cd is not working.

### ISSUE THREAD

**Issue by amosbird** [airblade/vim-rooter#37]
I've installed vim-rooter on Windows Vim 7.4. I started vim with --remote-tag-silent to keep only one instance. I have to manually type <leader>cd to change to the project root.

**Comment by airblade** [comment]
Maybe vim-rooter cannot identify the root of your project.  What should it be looking for?

Does it work when you start vim without `--remote-tag-silent`?

**Comment by amosbird** [comment]
@airblade When I manually type `<leader>cd`, vim-rooter can identify the root. And I tried vim without `--remote-tag-silent`, yes it works. Maybe we can refine vim-rooter a little bit to work with this option?

**Comment by amosbird** [comment]
Perhaps [this patch](https://groups.google.com/forum/#!topic/vim_dev/WLaddu-dXCQ) is the cure?

**Comment by amosbird** [comment]
I've tried manually adding `au BufReadPost * <Plug>RooterChangeToRootDirectory`, no good

**Comment by airblade** [comment]
Something to do with `--remote-tab-silent` is causing the problem.  However I have no idea what that might be.

**Comment by amosbird** [comment]
Is there any workaround?

**Comment by airblade** [comment]
I don't know.

Does it work on Vim 7.4.678 which you linked to above?

**Comment by amosbird** [comment]
@airblade Windows Vim doesn't show its patch version so I don't know if it works.

**Comment by amosbird** [comment]
It's pretty clear now that `--remote-tab-silent` will break a lot of autocmds.
