### ISSUE TITLE
Expose `s:FindRootDirectory` globally

### ISSUE THREAD

**Issue by rafi** [airblade/vim-rooter#38]
Can `s:FindRootDirectory` be exposed globally so other scripts can use this functionality?

**Comment by airblade** [comment]
What other scripts would want to use this?

**Comment by rafi** [comment]
Any custom functions within `vimrc` or personal home-made plugins that need the project's root path.

**Comment by rafi** [comment]
Functions for `tabline` or `statusline`, custom per project ctags compilation, per-project local .vimrc, and much more. It would be very helpful using this plugin as a utility library as-well (or instead) it's automatic behavior.

**Comment by airblade** [comment]
It's in 38a1b531.  Let me know how it works out for you.
