### ISSUE TITLE
rooter doesn't cd with tab change

### ISSUE THREAD

**Issue by haifengkao** [airblade/vim-rooter#40]
I am used to switching between different tab with `gT` and `gt`.
But I found that rooter doesn't always change the working directory automatically.
I have to call `:Rooter` manually to set the working directory to the correct folder.
Where I should look into this problem?

**Comment by airblade** [comment]
Are you using the latest version?

It should change directory on the[ `BufEnter`](https://github.com/airblade/vim-rooter/blob/a3b9500ebda69f90d16a567da9a39693919489ea/plugin/rooter.vim#L145) event.  You could start there, seeing whether the event triggers correctly.

**Comment by haifengkao** [comment]
Got it! It is caused by sourcing .vimrc.
