### ISSUE TITLE
Can not change to .git/ when open a new file in a new directory!

### ISSUE THREAD

**Issue by wsdjeg** [airblade/vim-rooter#41]
@airblade I hava test this plugin by default setting.
reproduce step:
1. now I am in `~/ ` my home directory;
2. I hava a git project in `~/sources/JavaLibs`,that means there is a dir named `~/sources/JavaLibs/.git/`;
3.Then I open a new file in a new directory in this project dir,for example;`~/sources/JavaLibs/src/main/java/com/testNewdir/newDir/New.java`
4.then the plugin does not works, echo getcwd() also show me `/home/wsdjeg/`,also same as https://github.com/artur-shaik/vim-javacomplete2/commit/e60daf8c916bde90a9e636fa5a8a1f51acc6fd1d can not fine pom.xml

**Comment by airblade** [comment]
I cannot reproduce the problem.

What does `:echo g:rooter_patterns` give you?

**Comment by wsdjeg** [comment]
@airblade are you sure you open a new file in a **new** directory?

**Comment by wsdjeg** [comment]
show me ['.git', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']

**Comment by wsdjeg** [comment]
check step:
```shell
cd ~
mkdir -p Test/.git
vim Test/testnew/test.vim
```

**Comment by airblade** [comment]
I still can't reproduce it.  Here's what I get:

```sh
cd ~
mkdir -p Test/.git
vim Test/testnew/test.vim

:echo getcwd()
/Users/andy/Test
```

I don't know why it's not working for you.  Are you running the latest version?  What does `:echo g:rooter_autocmd_patterns` produce?

**Comment by wsdjeg** [comment]
:echo g:rooter_autocmd_patterns
show me ['.git', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']

**Comment by wsdjeg** [comment]
ok I wil start a new branch to find what is going on!

**Comment by airblade** [comment]
`:echo g:rooter_autocmd_patterns` should give `*` if you haven't changed it...

**Comment by wsdjeg** [comment]
test with this branch's vimrc
https://github.com/wsdjeg/DotFiles/tree/test_vim_rooter
test step:
```
cd ~
mkdir -p Test/.git
vim Test/testnew/test.vim

:echo getcwd()
/home/wsdjeg
```
![2016-01-25 20 20 32](https://cloud.githubusercontent.com/assets/13142418/12550842/41569cde-c3a1-11e5-853e-883ceee145fd.png)

**Comment by wsdjeg** [comment]
Maybe it is the issue of neobundle?

**Comment by airblade** [comment]
Very strange.  I doubt NeoBundle is the problem.

All I can suggest is you step through vim-rooter's code to see where it is going wrong.  The code is pretty short so it won't take long.

**Comment by wsdjeg** [comment]
I have finish readding the src of vim-rooter,I think the plugin is sourced after enter the new buffer

**Comment by wsdjeg** [comment]
@Shougo do you use vim-rooter?I think maybe you know why this issue happened! thanks a lot

**Comment by wsdjeg** [comment]
only oneline in my vimrc still can encount this issue
```vim
source /home/wsdjeg/.vim/bundle/vim-rooter/plugin/rooter.vim
```

**Comment by wsdjeg** [comment]
I got it @airblade 
if s:IsVirtualFileSystem() || !s:IsNormalFile()
   **return**
empty(&buftype) == 1
match(expand('%:p'), '^\w\+:[\/][\/].*') != -1 == 0
so this issue is appeared

**Comment by airblade** [comment]
So it's saying you are opening a "virtual" file.  What does `:echo expand('%:p')` produce?

**Comment by wsdjeg** [comment]
show me `Test/testnew/test.vim`

**Comment by airblade** [comment]
That doesn't make sense: according to your output above, the `s:IsVirtualFileSystem()` function returns true.  But the regexp doesn't match.

What does `:echo match(expand('%:p'), '^\w+:[\/][\/].*')` produce?

**Comment by wsdjeg** [comment]
`echo match(expand('%:p'), '^\w+:[\/][\/].*')` show me -1

**Comment by wsdjeg** [comment]
if the dir testnew exists ,echo expand('%:p') show me `/home/wsdjeg/Test/testnew/test.vim`

**Comment by airblade** [comment]
OK, that's what I'd expect.  I don't think these lines are returning:

```viml
if s:IsVirtualFileSystem() || !s:IsNormalFile()
  return
endif
```

Were you saying that the function is returning here?

**Comment by wsdjeg** [comment]
ok let me do more test now,sorry for the wrong info!

**Comment by wsdjeg** [comment]
what is your os?really strange,why you can not reproduce this issue.

**Comment by airblade** [comment]
OS X 10.11.2, MacVim 7.4.969.  What is your OS?

**Comment by wsdjeg** [comment]
ubuntu 14.04, ok ,let me test in gvim now

**Comment by wsdjeg** [comment]
can you test it with my vimrc bransh,I think maybe you auto mkdir before enter a bufder

**Comment by airblade** [comment]
I tried this on Ubuntu and reproduced the problem.  The key line is [here](https://github.com/airblade/vim-rooter/blob/a3b9500ebda69f90d16a567da9a39693919489ea/plugin/rooter.vim#L76):

```viml
let match = finddir(a:pattern, dir_current_file . ';')
```

Here `dir_current_file` is `Test/testnew`.

The `finddir(name, path)` functions looks for directory `name` in `path`.  The directory `Test/testnew` doesn't exist on the file system so `finddir()` doesn't find a match...on Ubuntu.  On OS X it does.

A workaround is to run vim-rooter manually after the first time you save a file in a new directory which didn't exist before.  You can run vim-rooter manually with `:Rooter`.

**Comment by airblade** [comment]
Here's a simple reproduction:

```
$ mkdir foo && cd foo
$ mkdir .bar
$ vim quux/baz.vim

[in vim]
:echo finddir('.bar/', 'quux;')
```

On OS X you get `.bar/` and on Ubuntu you get an empty string.

**Comment by wsdjeg** [comment]
yes,that is just what I am saing,you can see 
https://github.com/artur-shaik/vim-javacomplete2/commit/e60daf8c916bde90a9e636fa5a8a1f51acc6fd1d

**Comment by airblade** [comment]
That's different: it uses `findfile()`.

**Comment by wsdjeg** [comment]
`echo finddir('.bar/', 'quux;')` show empty string


> [in vim] :echo finddir('.bar/', 'quux;')

are you sure is not echo finddir('.bar/', 'foo;')

**Comment by airblade** [comment]
Yes, I'm sure.  The second argument is the directory containing the file you are editing (whether or not it actually exists).  See [above](https://github.com/airblade/vim-rooter/issues/41#issuecomment-174943798).

**Comment by wsdjeg** [comment]
but if using `echo finddir('.bar/')` show me `.bar/`

**Comment by wsdjeg** [comment]
same as https://github.com/artur-shaik/vim-javacomplete2/commit/e60daf8c916bde90a9e636fa5a8a1f51acc6fd1d  
just move the second args

**Comment by wsdjeg** [comment]
why use ';'  not ':'

**Comment by wsdjeg** [comment]
@airblade  sorry for my missunderstand,I will try to find how to fix it.
