### ISSUE TITLE
Vim filename/path completion

### ISSUE THREAD

**Issue by rrbarbosa** [airblade/vim-rooter#43]
Before using vim-rooter, I had `set autochdir`, so that the current folder was always the active buffer folder. This was great in combination with filename completion ([`compl-filename`](http://vimdoc.sourceforge.net/htmldoc/insert.html#compl-filename)) .

Since I started using [`airblade/vim-rooter`](https://github.com/airblade/vim-rooter), the filename completetion starts from the project folder, which can be a pain in some projects.

Is there a way to make the filename completion use the directory of the active buffer instead of the current directory? Or some other workaround?

[Also asked in stackoverflow](http://stackoverflow.com/questions/35321300/vim-filename-path-completion)

**Comment by airblade** [comment]
The last sentence of `:h compl-filename` says:

> Note: the 'path' option is not used here (yet).

Therefore I think filename completion always starts from the current directory.

It's not quite the same but you can navigate down through your directories by `C-X C-F`ing on directory names.

I can think of two possible workarounds:

- Write a little custom filename completion function which would change directory to the current buffer's directory, list the files, then change directory back again afterwards.  You would invoke it with `C-X C-U`.
- Use a fuzzy file finder.  I'm not sure if any of them present matches in an autocomplete window but hopefully some do.

**Comment by airblade** [comment]
Closing this because it's outside the scope of the plugin.  Sorry!
