### ISSUE TITLE
Working with vim sessions

### ISSUE THREAD

**Issue by simonsmith** [airblade/vim-rooter#44]
First, thanks for this plugin, it's excellent.

One use case I have trouble with is if I have various files open in different directories and using sessions. Obviously the plugin works great with changing the root, but when I close and open a session it seems to lose the changes. Is this something I can get working?

I use [vim-session](https://github.com/xolox/vim-session).

**Comment by airblade** [comment]
I don't use sessions so I'm not quite sure what's not working.

Is it that when you restore a session, but before you do anything, the directory isn't set to the active buffer's root?

**Comment by simonsmith** [comment]
I think I've managed to reproduce it. I think the issue stems from having tabs open too, so it might be quite an edge case.

If I have two buffers open:

```
/foo/file.js
bar/styles.css
```

Open each in a tab as well, then switch to `styles.css` and quit Vim (saving my session as it happens).

When I restore the session it correctly opens the two files, but also create an empty buffer, like so:

```
/foo/file.js
bar/styles.css
bar/file.js <-- empty buffer
```

Using just buffers (no tabs) with sessions seems to work fine, so this is probably not worth a fix, as I can just shut that extra buffer.

Feel free to close :)

**Comment by airblade** [comment]
Er, ok, thanks!

**Comment by john-kurkowski** [comment]
I worked around this issue with a standard option in my .vimrc:

```vim
set sessionoptions-=curdir
```

When `curdir` and `sesdir` are both unset (the latter is unset by default), sessions track buffers with absolute paths. Then vim-rooter can't effect sessions. I suppose the downside is sessions with relative paths are more portable.
