### ISSUE TITLE
E117: Unknown function: FindRootDirectory

### ISSUE THREAD

**Issue by whitesiroi** [airblade/vim-rooter#45]
I have this lines in my `.vimrc`

```
NeoBundle "airblade/vim-rooter"

" The public function FindRootDirectory() returns the absolute path to the root directory as a string, if a root directory is found, or an empty string otherwise.
let g:rooter_patterns = ['.git/']
let g:rooter_manual_only = 1
let g:rooter_disable_map = 1

let &makeprg=FindRootDirectory()."/app/Console/cake test %:p"
```

And I'm getting this errors after running the vim command:
```
E117: 未知の関数です(Unknown function): FindRootDirectory
E15: 無効な式です(Invalid expression): FindRootDirectory()."/app/Console/cake test %:p"

```
It does work, but how can I get rid from the messages?

I'm also using it with `nnoremap` without any errors like:
`nnoremap <leader>t :exe "!clear; ".FindRootDirectory()."/app/Console/cake test %:p"<CR>`
Only getting error messages with `let &makeprg=FindRootDirectory()."/app/Console/cake test %:p"`

Thank you.

**Comment by whitesiroi** [comment]
Sorry, it does work this way.
autocmd VimEnter * let &makeprg=FindRootDirectory()."/app/Console/cake test %:p"

Thank you.

**Comment by airblade** [comment]
Glad you got it working!
