### ISSUE TITLE
Suggestion: configuration option for directory when a non-project file is open

### ISSUE THREAD

**Issue by motdef** [airblade/vim-rooter#46]
I usually find that when I'm working on a non-project file I like to have my directory set to $HOME so that I can find any other non-project file in my home directory when invoking plugins like fzf or CtrlP. Would it be possible to add a configuration option so that the (local) directory is set to $HOME, or any arbitrary directory, when switching from a project file to a non-project file?

**Comment by airblade** [comment]
Yes, that sounds possible.  I'll try to find the time soon!

**Comment by airblade** [comment]
Add this to your vimrc:

```viml
let g:rooter_change_directory_for_non_project_files = 'home'
```
