### ISSUE TITLE
Rooter while in file explorer?

### ISSUE THREAD

**Issue by nhooyr** [airblade/vim-rooter#47]
Rooter currently only works for normal files, is it possible we can add support for rooting directories that are open in a file explorer?

**Comment by airblade** [comment]
I think that should be possible.  I'll try to make some time soon to have a go.

**Comment by nhooyr** [comment]
https://github.com/airblade/vim-rooter/blob/master/plugin/rooter.vim#L50

All we need to do is change that if statement to `empty(&buftype) || isdirectory(expand('%'))`. and then rename the function of course.

**Comment by balaclark** [comment]
Files opened via the vim-startify recent items list are also not rooted.

**Comment by airblade** [comment]
@nhooyr @balaclark Fixed as of b287094.
