### ISSUE TITLE
use bang to switch behaviour between lcd and cd

### ISSUE THREAD

**Issue by nhooyr** [airblade/vim-rooter#48]
Sometimes I want to `lcd`, sometimes I want to `cd`. The use of the bang is a nice convenience for swapping the behaviours. Using the bang causes `:rooter` to do the opposite of whatever it's set to by default. Right now I'm just doing this:

```vim
function! s:rooter(lcd)
  if a:lcd
    let g:rooter_use_lcd = 1
  else
    let g:rooter_use_lcd = 0
  endif
  Rooter
endfunction
nnoremap <silent> <unique> <Leader>gl :call <SID>rooter(1)<CR>
nnoremap <silent> <unique> <Leader>gc :call <SID>rooter(0)<CR>
```

**Comment by airblade** [comment]
It's not obvious to me that `Rooter!` would toggle `cd` and `lcd`.  I'm not inclined to add functionality just to toggle a config option: it feels like the extra code isn't worth it.
