### ISSUE TITLE
E172: Only one file name allowed: :lcd /MY/FILE LOCATION

### ISSUE THREAD

**Issue by GregorySchwartz** [airblade/vim-rooter#52]
Since recently updating, I get this error message when switching from window to window, each time:

Error detected while processing function <SNR>19_ChangeToRootDirectory[16]..<SNR>19_ChangeDirectory:                                                                                        

line 3: 

E172: Only one file name allowed: :lcd /MY/FILE LOCATION

I'm not sure what could be causing it, but I think it must be vim-rooter because of ChangeToRootDirectory being the culprit. I never ran into this issue in the past and my configuration file has not changed (other than running PlugUpdate). I should mention that in this case, FILE LOCATION has a space in it, not sure if that matters, just thought it might because it said only one file name allowed. Also, I'm using neovim.

**Comment by airblade** [comment]
Thanks for reporting this.
