### ISSUE TITLE
On Pane Switch

### ISSUE THREAD

**Issue by jcarlos7121** [airblade/vim-rooter#53]
Hi guys! hey, not sure if its  something that i did or a change that happened lately. From time to time i used to open a 2 dual view with 2 scripts on my vim, both of them could be part of different project roots.

Whenever i change to each another in the dual panel view, i could open a shell with :!bash and it will take me directly to the root of that project flawlessly.

But now whenever i change between panels, the root always stays on to the last root project i opened.

Does something changed? or do i need to add another config for this to work like before?

**Comment by airblade** [comment]
Hi!

vim-rooter's behaviour shouldn't have changed so it should still work like it did before.  Is your vim-rooter up to date?  Do you have any vim-rooter configuration?

I tried to reproduce your problem but wasn't able to.  Please can you send me steps to reproduce it?

**Comment by jcarlos7121** [comment]
Sure sure.

Step 1. Open a 2 Pane view, with 2 scripts on each side, each Script should belong to a different root directory project.

Example:

2 side views/or tabs
Gemfile
  Root directory: /home/user/projects/cool_project1

Anotherfile.js
  Root directory: /home/user/projects/cool_project2

Wheneve i change with Ctrl + L or Ctrl + H, or between tabs, the Root directory is not updated, the
PWD command always shows me the last opened root directory project.

Here i share a asciicinema recording:

https://asciinema.org/a/4gc0084i3heauyeb5eky20myj

Hope you guys know what is happening.

**Comment by airblade** [comment]
What do you have Ctrl-L / Ctrl-H mapped to?

**Comment by airblade** [comment]
This works for me.  Does it work for you?

1. Open Vim.
2. Edit a file from project A.
3. Verify current working directory is project A's (`:pwd`).
3. Split the window (`Ctrl-W s`)
4. Go to new window (`Ctrl-W j`) and edit a file from project B.
5. Verify current working directory is project B's (`:pwd`).
6. Jump between the windows (`Ctrl-W w`) and verify working directory is correct each time.

**Comment by airblade** [comment]
Are both projects in git?

**Comment by airblade** [comment]
Does vim-rooter work when it is your only installed plugin?  It's possible another plugin you added or updated recently conflicts.

**Comment by jcarlos7121** [comment]
Yep, it is some other plugin installed, i disabled literraly all my plugins and the behaviour now works, ill try reenabling them one by one to see the one that causes the conflict

**Comment by jcarlos7121** [comment]
yeah both projects are on git

**Comment by airblade** [comment]
Let me know which plugin conflicts when you figure it out...

**Comment by jcarlos7121** [comment]
NERDTree is the one that gets me conflicts :/, with the NERDTree bundle installed, and no config made to NERDTree, the vim-rooter is not working at all

**Comment by jcarlos7121** [comment]
Hi guys!, i got news, so with neobundle i was going back throught the commits using the specific revisions in the project, and i found that before this commit, everything is working pretty cool for me.

https://github.com/airblade/vim-rooter/commit/b287094dc1baf1d4ba43e3c27d5ce45868c8f920

i am using the commit before which is thise one.

https://github.com/airblade/vim-rooter/commit/f4dad3392fc1488cfd145e23429cc3cf72db7541

I am using it with neobundle in my .vimrc like this (just in case someone needs a workaround).

`NeoBundle 'airblade/vim-rooter', { 'rev' : 'f4dad3392fc1488cfd145e23429cc3cf72db7541' }`

**Comment by airblade** [comment]
You have NERDTree configured to [change the current working directory whenever the tree root is changed](https://github.com/jcarlos7121/dotfiles/blob/8eece08d2cce09c29320fff3008db7feb016986f/home/.vimrc#L267).

If you have vim-rooter you don't need NERDTree to change the current working directory, so remove that line from your vimrc.

**Comment by airblade** [comment]
Closing because I think I found the problem and I haven't heard anything to the contrary.
