### ISSUE TITLE
Doesn't seem to detect project directories anymore

### ISSUE THREAD

**Issue by tssund93** [airblade/vim-rooter#54]
With a minimal vimrc that only has the necessary lines to install vim-rooter with Vundle, it doesn't seem to detect the root directory of projects anymore.  I've tested with both git and SVN repositories.  If I change to a file in a project when g:rooter_change_directory_for_non_project_files is equal to '' (the default), the directory doesn't change, and if I set it to 'current', it always sets to the directory of the file, even if it's in a subdirectory of a project.  Unless there was a default change that I didn't see when looking at the changelog, this seems to be a bug.

This is on Windows 10, GVim version 7.4.827.

**Comment by airblade** [comment]
I'm away this week...I'll take a look when I get back.

**Comment by airblade** [comment]
Thanks for the clear description of the problem.  It's a bug.

Please could you add `echom "should change directory for ".s:fd` to [line 124](https://github.com/airblade/vim-rooter/blob/8d60e073f34f1879446c2180237dbbacdc2b6f9e/plugin/rooter.vim#L124) and verify you see the message?  Assuming you see it, what is the path at the end of the message?

**Comment by tssund93** [comment]
I do see it, here's the message:
![2016-06-13 08_42_33-rooter vim _vimfiles_bundle_vim-rooter_plugin - gvim](https://cloud.githubusercontent.com/assets/3605522/16007888/f28db6b8-3142-11e6-8def-43c61a6cf31c.png)

Thanks for the quick reply.

**Comment by airblade** [comment]
Well that looks perfectly normal.

What's the "root" directory for that file?  I.e. what directory are you expecting vim-rooter to change to?

**Comment by tssund93** [comment]
Previously, it would have changed to the root directory of the git project (~\vimfiles\bundle\vim-rooter), now it doesn't detect the root directory and either changes to the file's directory (~\vimfiles\bundle\vim-rooter\plugin) or doesn't change at all, depending on what I have g:rooter_change_directory_for_non_project_files set to.

**Comment by airblade** [comment]
Just to confirm, does `~\vimfiles\bundle\vim-rooter` have a `.git/` directory?

**Comment by tssund93** [comment]
It does:
![image](https://cloud.githubusercontent.com/assets/3605522/16008834/e5b65c88-3147-11e6-99fa-4fb0e9f6a92d.png)

**Comment by airblade** [comment]
In Vim what does this produce: `:echo fnameescape("C:\Users\developer\vimfiles\bundle\vim-rooter\plugin\rooter.vim")`?

**Comment by tssund93** [comment]
Vim outputs the following when I run that:

C:Usersdevelopervimfiles^Hundlevim-rooterplugin

ooter.vim

**Comment by airblade** [comment]
That's really weird.  Can you post a screenshot?

**Comment by tssund93** [comment]
Here's what it looks like in the command window:
![image](https://cloud.githubusercontent.com/assets/3605522/16009202/a98cd82a-3149-11e6-9d88-74f77a887bd7.png)

**Comment by tssund93** [comment]
I just ran `echo fnameescape("C:\Test\Logs\Test1234.txt")` and it outputted the following:

`C:TestLogsTest1234.txt`

**Comment by airblade** [comment]
Ok, thanks.  I'm trying to establish whether [this line](https://github.com/airblade/vim-rooter/blob/8d60e073f34f1879446c2180237dbbacdc2b6f9e/plugin/rooter.vim#L77) is working properly on your system.

It looks like `fnameescape()` is treating the backslashes as escape characters instead of legitimate path separators.

**Comment by airblade** [comment]
What does `:echo &isfname` give?

**Comment by tssund93** [comment]
`@,48-57,/,\,.,-,_,+,,,#,$,%,{,},[,],:,@-@,!,~,=`

**Comment by airblade** [comment]
Please can you try the slashes-54 branch and let me know if it solves the problem?

**Comment by tssund93** [comment]
I found out what was causing the problem.  The fnameescape problem was just a wild goose chase because while Vim doesn't display the path correctly, internally it seems to know how to handle it.  Let me know if you think the way I fixed it is alright.

**Comment by airblade** [comment]
Before b287094 the code passed a directory to `finddir()` and `findfile()` so I think you're right that passing a file path instead is the problem.  Interesting though vexing that it doesn't seem to matter on unix.

Closed as per #55.
