### ISSUE TITLE
Would you please add a license?

### ISSUE THREAD

**Issue by jordwalke** [airblade/vim-rooter#57]
I would appreciate it!

**Comment by airblade** [comment]
Here you go: c92dfe2.

Thanks for pointing out the lack of a licence!

**Comment by jordwalke** [comment]
Nice choice on MIT, @airblade !

I wish I could depend on this from within another plugin I want to build, but there's no standard way of doing so with Vim plugins it seems, so my only hope is to *embed* this plugin inside of my plugin (the license helps me do that). I appreciate the library. I wish anyone could just add a "dependency" on this library from their own, so that people could use this as a reusable utility. So many projects roll their own version!

**Comment by airblade** [comment]
I agree – there really should be a way to declare dependencies for plugins.  Then all sorts of utility libraries could spring up, saving everyone time and effort.
