### ISSUE TITLE
Deosn't work with `vim --remote`

### ISSUE THREAD

**Issue by wzhliang** [airblade/vim-rooter#61]
I usually keep a single gvim session open and use `gvim --remote <file>` to send new files to it. But this doesn't seem to work with vim-rooter.

**Comment by airblade** [comment]
Works for me with mvim.

vim-rooter runs on `BufEnter` (see [here](https://github.com/airblade/vim-rooter/blob/c92dfe299b365449dd4ea46860494affca51ff05/plugin/rooter.vim#L164)) so, as long as `gvim --remote <file>` triggers `BufEnter`, the plugin should run.

I think the simplest way to debug this is for you to add `echom` statements to your installed version of vim-rooter, starting with the autocommand, to see where it's going wrong.

**Comment by wzhliang** [comment]
What's mvim?
I tried on both MacVim and vim-gtk and both behave the same. Perhaps vim should fire the event and not? I'll dig some more when I find some time.

**Comment by airblade** [comment]
mvim is the helper script which comes with MacVim.  It simply launches MacVim.

I couldn't reproduce this with MacVim.  Perhaps you could post step by step instructions to reproduce this?

**Comment by anpol** [comment]
Steps to reproduce:
1. Close all instances of MacVim.app
2. From the terminal, `cd` somewhere within some project directory tree.
3. Run `gvim --remote-tab-silent SOME_FILE`
4. In gvim, run `:pwd`. Directory displayed is the current directory of terminal, not the project root directory.

Similar issue described here: http://vi.stackexchange.com/q/2066

It started working as expected after adding `autocmd BufReadPost * :Rooter`.

**Comment by airblade** [comment]
@anpol Thanks for the reproduction steps, the linked SE question, and a workaround :)

@wzhliang I think your best bet is to add `autocmd BufReadPost * :Rooter` to your vimrc.
