### ISSUE TITLE
i'd like use this with NERDTree, but NERDTree is not change root after i change buffer to another project

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [airblade/vim-rooter#62]
vim-rooter has changed the root. NERDTree not work even i set NERDTreeChDirMode=2. i know it's NERDTree's problem, how to avoid it?

**Comment by airblade** [comment]
If you use both vim-rooter and nerdtree, you need to set `NERDTreeChDirMode` to `0`.  Otherwise vi-rooter and nerdtree will both be trying to change the directory.

**Comment by ipelekhan** [comment]
Have the same problem. gVim on Windows. **vim-rooter** changes the root directory, but NERDTree not. I have checked, ```NERDTreeChDirMode``` is ```0``` by default. Do you have any tips how to resolve this issue?
