### ISSUE TITLE
Run when starting vim with no buffer?

### ISSUE THREAD

**Issue by KyleAMathews** [airblade/vim-rooter#63]
My habit is to start vim when I need to edit a file somewhere in the project. But I often just run `vim` as I don't remember the exact file name and want to do a file search after opening.

But currently this plugin doesn't run until after I open a buffer. So I open any random file and then do a file search (using vim-fzf).

Is there a way to run vim-rooter even without a buffer open on starting vim?

**Comment by airblade** [comment]
Currently the plugin [relies on a buffer being open](https://github.com/airblade/vim-rooter/blob/c92dfe299b365449dd4ea46860494affca51ff05/plugin/rooter.vim#L120).

It should be feasible to make it use the current directory instead if no buffer is open.

Then you could use `autocmd VimEnter * :Rooter`.

**Comment by airblade** [comment]
Try this: aaac408.

**Comment by KyleAMathews** [comment]
That worked! Thanks :-)
