### ISSUE TITLE
i need very simple mode, I think most of programmer need it!!

### ISSUE THREAD

**Issue by wellcomez** [airblade/vim-rooter#64]
I always start vim under folder which is project's root folder. There are tags and cscope.out under this folder. While i read code, current folder will be change current file. This will cause ctag no work.
My requirement is simple no need find vcs ,just folder open by vim is enough

**Comment by airblade** [comment]
If you always start Vim in the directory which is the project's root directory, you don't need any plugin.  Vim will always keep that directory as its working directory (as long as you haven't turn on the `autochdir` option).

**Comment by whateverdev** [comment]
I had the same problem...

The solution I tried and it works

Add to your `.vimrc`

```
 let my_ = expand("%:p:h")
 nmap <C-p> :Files <C-R>=my_<CR><cr>
```
Save vim start folder and pass this as argument in `:Files`
