### ISSUE TITLE
auto change root to git submodule

### ISSUE THREAD

**Issue by drinksober** [airblade/vim-rooter#65]
when I edit a file which is belongto a git submodule, this plugin will auto change the project root to the submodule, but I want to keep the root to the main git repo

I think this command can help to solve this problem, it show current repor is a submodule  or not...
 
git rev-parse --show-superproject-working-tree

**Comment by airblade** [comment]
If you never want the root changed to the git submodule's root, you can set this in your vimrc:

```viml
let g:rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
```

(Feel free to get rid of the other version control system patterns if you want.)

**Comment by airblade** [comment]
I'm assuming this is fixed but let me know if it's still a problem.
