### ISSUE TITLE
wildcard patterns are not supported

### ISSUE THREAD

**Issue by bhenderson** [airblade/vim-rooter#66]
Backstory: Go projects are typically setup so that subdirectories act as independent projects.

I love this plugin (thank you!). Sometimes in subdirs, I'd like to disable it.

One way I thought of fixing my issue was by appending `['*.go']` to g:rooter_patterns but `findfile` doesn't support wildcards in the name argument.

I'm not a vim script expert. I tried changing it to glob, which does support wildcards, but it doesn't support upwards search.

do you have any thoughts?

thanks,

**Comment by airblade** [comment]
Could you put a `.root` file in each subdirectory and prepend that to `g:rooter_patterns`?

**Comment by bhenderson** [comment]
that's what I ended up doing, but not my favorite having extra files. But this issue doesn't come up a lot, so I'll just close and see if I can figure anything else out next time.

thanks,

**Comment by airblade** [comment]
I agree, extra files aren't ideal.  Do Go projects typically have certain files in their top directory / subdirectories?

A related approach would be to add the names of the subdirectories to `g:rooter_patterns`.  It's a bit hacky but it should work.  Potentially you could script it with vim-projectionist.
