### ISSUE TITLE
Rooter ignores extensions

### ISSUE THREAD

**Issue by casey** [airblade/vim-rooter#71]
It looks like findfile ignores extensions, which can make rooter chdir to the wrong place. For example, if `g:rooter_patterns = ['baz']`:

```
mkdir -p foo/bar
touch foo/bar/baz.rs
toch foo/baz
vim foo/bar/baz.rs
```

Rooter will chdir to `foo/bar`, since findfile ignores extensions, and will return `baz.rs`, even though that's probably not what we wanted.

I tried it with `baz.txt`, and it chdired to `foo`, so I'm wondering if it has something to do with the `.rs` extension. I tried `.js` and it had the same effect as `.rs`.

I confirmed that this was due to `findfile()` by running `:echo findfile('baz')`. While editing `foo/bar/baz.rs` it would return `baz.rs`. When I changed the name of the file to `baz.txt`, it returned `baz`, so it looks like this is due to findfile.

**Comment by airblade** [comment]
I had never noticed this before.

The docs for `findfile()` include:

> Uses 'suffixesadd'.

And the docs for `suffixesadd` say:

> 	Comma separated list of suffixes, which are used when searching for a
>	file for the "gf", "[I", etc. commands.  Example:
>		:set suffixesadd=.java

It defaults to an empty string.

From your report I would guess that you have `suffixesadd` set to `.txt`.  Please could you check?

```viml
:verbose set suffixesadd?
```

**Comment by casey** [comment]
Ahh, okay, that's the problem. It looks like the language support plugins I have installed all add extensions to suffixesadd:

```
suffixesadd=.rs
  Last set from ~/src/local/etc/vim/plugged/rust.vim/ftplugin/rust.vim
```

```
suffixesadd=.js
  Last set from ~/src/local/etc/vim/plugged/vim-javascript/after/ftplugin/javascript.vim
```

Would it be possible to set suffixesadd to '' in `s:FindAncestor` and then restoring it to its original value before returning?

**Comment by casey** [comment]
Just tried the new version and it's fixed. Thank you very much 💖
