### ISSUE TITLE
How to config priority?

### ISSUE THREAD

**Issue by wsdjeg** [airblade/vim-rooter#73]
ref: https://github.com/SpaceVim/SpaceVim/issues/1176

```vim
function! s:SearchForRootDirectory()
  for pattern in g:rooter_patterns
    let result = s:FindAncestor(pattern)
    if !empty(result)
      return result
    endif
  endfor
  return ''
endfunction
```

@airblade In this func, it will only find the first match path and return it, what I want is to find the longest path. so how could we config it?

**Comment by airblade** [comment]
```viml
function! s:SearchForRootDirectory()
  for pattern in g:rooter_patterns
    let result = s:FindAncestor(pattern)
    if !empty(result)
      return result
    endif
  endfor
  return ''
endfunction
```

**Comment by wsdjeg** [comment]
@airblade This looks nice, that means it will find all the root paths, and return the first one base on a custom sort_function.

**Comment by wsdjeg** [comment]
@airblade why this issue is closed?

**Comment by airblade** [comment]
I closed it because there's the outline of a solution which you can use in a fork.  The problem being solved isn't one which I think vim-rooter should solve.

**Comment by wsdjeg** [comment]
I got it, thanks.
