### ISSUE TITLE
Newbie trying to catch the event RooterChDir

### ISSUE THREAD

**Issue by degyves** [airblade/vim-rooter#79]
So, I'm trying to catch the RooterChDir. Unfortunately, after googling around, I'm stuck with this one. 

I've created the following vim function under my vim init file:

```
function! ConfigureChDir()
  echom "hello, world!"
endfunction
" Call after vim-rooter changes the root dir
autocmd User RooterChDir call ConfigureChDir()
```

So I expect tha after a few changes something should appear on the :messages. But nothing appears, so something is wrong with my code. Can you give some hints/tell which is the error?

**Comment by airblade** [comment]
Does it work if you remove `User` from your `autocmd` line?

**Comment by degyves** [comment]
If I remove `User` it says:

Error detected while processing /Users/degyves/.config/nvim/init.vim:
line  754:
E216: No such group or event: RooterChDir call ConfigureChDir()
"~/.config/nvim/plugged/vim-rooter/plugin/rooter.vim" 191L, 4515C

**Comment by airblade** [comment]
Yes, I think you were right originally with the `User`.  Sorry about that.

Are you sure you are triggering a directory change by editing files in different "roots"?

**Comment by degyves** [comment]
Yes, double-checked it with `:Ex`, also by changing with `:e ~/.config/nvim/init.vim`, and to other folders (e.g pom.xml for a java project) so when I do `:e <tab>` I can see that effectively vim-rooter has changed the root folder so I get the current list of files on the current folder:

Opening a file declared at the g:rooter_pattern:

![screen shot 2018-09-05 at 5 35 53 am](https://user-images.githubusercontent.com/2539124/45088093-a3576c80-b0cd-11e8-8850-709a9dad8c5d.png)

so with `:e <tab>`:

![screen shot 2018-09-05 at 5 36 06 am](https://user-images.githubusercontent.com/2539124/45088109-ac483e00-b0cd-11e8-953d-b1556fc549ef.png)

But nothing appears at the messages buffer:

![screen shot 2018-09-05 at 5 38 15 am](https://user-images.githubusercontent.com/2539124/45088223-f6312400-b0cd-11e8-88c1-4d2cdbcbe6f4.png)

**Comment by airblade** [comment]
Your `ConfigureChDir()` function was being executed but it was executed silently, which meant your message didn't show up.

The silence was to avoid an error message if no autocmd handler had been defined – but there's a better way to do it which I just committed.

**Comment by degyves** [comment]
Oh, I've just seen it! Thank you very much @airblade !
