### ISSUE TITLE
Could vim-rooter add a path(both directory and filename) to g:rooter_patterns

### ISSUE THREAD

**Issue by t6ui** [airblade/vim-rooter#85]
I need an rooter_pattern naming "build/envsetup.sh" to specify that current project is an AOSP( Android Open source Project).
Could this  be realized?

**Comment by airblade** [comment]
vim-rooter users `findfile()` to look for files, starting at the current directory and looking upwards.

https://github.com/airblade/vim-rooter/blob/d5bb76e31c030e6b9197491ff521eca49332564b/plugin/rooter.vim#L88

Specifying a path fragment, e.g. `build/envsetup.sh` will work if you are below the `build/` directory but not elsewhere in the project (I think).  You can test with `:echo findfile('build/envsetup.sh', '.;') from various locations.

`finddir()` and `findfile()` work well for the plugin so I don't want to move away from them.  I'm not sure how to support your use case though.

**Comment by airblade** [comment]
Good to hear `findfile()` does what you want.

Please try this patch to `s:IsDirectory()`:

```diff
diff --git i/plugin/rooter.vim w/plugin/rooter.vim
index e9df065..1521e7c 100644
--- i/plugin/rooter.vim
+++ w/plugin/rooter.vim
@@ -52,7 +52,7 @@ function! s:ChangeDirectory(directory)
 endfunction
 
 function! s:IsDirectory(pattern)
-  return stridx(a:pattern, '/') != -1
+  return a:pattern[-1:] == '/'
 endfunction
 
 function! s:ChangeDirectoryForBuffer()
```

If that works, the next problem will be that the code will change to the directory of the matched file, i.e. `build/`.

https://github.com/airblade/vim-rooter/blob/d5bb76e31c030e6b9197491ff521eca49332564b/plugin/rooter.vim#L108

I assume you want `build/`'s parent directory?  In which case the second argument to `fnamemodify()` will have to walk up the appropriate number of levels.

**Comment by t6ui** [comment]
It works as you said.
And I comment out some statements, it also run fine as I want. 
I don't know how to edit nice "diff code" like yours, so my modification is as follows:
```
   " if s:IsDirectory(a:pattern)
     " If the directory we found (`match`) is part of the file's path,
     " it is the project root and we return it.  Otherwise, the directory
     " we found is contained within the project root, so return its parent
     " i.e. the project root.
     let fd_match = fnamemodify(match, ':p:h')
     if stridx(fd_dir, fd_match) == 0
       return fd_match
     else
       return fnamemodify(match, ':p:h:h')
     endif
   " else
   "   return fnamemodify(match, ':p:h')
   " endif
``` 
Can this change be applied to your repository?

Thanks.

**Comment by airblade** [comment]
I've just made a couple of changes.  Please could you update and see whether it works the way you want?

**Comment by airblade** [comment]
I'm assuming this works for you but let me know if you'd like me to reopen this.
