### ISSUE TITLE
Problem if directory name starts with .git

### ISSUE THREAD

**Issue by jlesquembre** [airblade/vim-rooter#86]
In my project I have a `.git-hooks` directory with shared git hooks. E.g.:
```
├── a.txt
└── .git-hooks
    └── b.txt
```
If I open the file `b.txt` vim rooter changes the directory to `project/.git`.

**Comment by airblade** [comment]
It looks like 6a68f17 broke this.  I'll work on a fix.

**Comment by jlesquembre** [comment]
Thanks for your work on vim-rooter and for fixing this issue.
I just tested it and works :+1:

**Comment by airblade** [comment]
Great!  Thanks for confirming.
