### ISSUE TITLE
perhaps g:rooter_silent_chdir could default to true?

### ISSUE THREAD

**Issue by sanga** [airblade/vim-rooter#91]
So I updated vim-rooter and now it forced me to hit enter and extra time whenever running vim. Of course that behaviour can be overridden by setting `rooter_silent_chdir`, but perhaps if a user installs vim-rooter they should expect that the root is changed (the clue is in the plugin title ;) ) rather than explicitly setting a var to disable this?

Failing that, perhaps the message could be changed to something like "cwd: $CWD (please set rooter_silent_chdir to disable this message)"?

**Comment by airblade** [comment]
That's odd; I never get the hit-enter prompts.

What does this print?  `:echo &shortmess &cmdheight`

**Comment by airblade** [comment]
Also vim-rooter has echoed the directory for ages.  Do you know what commit you upgraded from?

**Comment by sanga** [comment]
I'm not sure. Anecdotally it was rather recently. It's possible that this is due to some other update (neovim for example, btw this is on recent neovim master - apologies for not mentioning that earlier) and not vim-rooter at all actually. That cmd returns `filnxtToOFcI 1`. I don't believe I have touched shortmess or cmdheight in a very long time.

**Comment by kkew3** [comment]
I just installed this plugin today. I encountered the exact same issue. I'm on macOS 10.14.4 system vim 8.0. It happened whenever I installed this plugin, and goes away if I removed it. Yeah, a hint pointing to that option in the message should be of great help.

**Comment by alanxoc3** [comment]
Hey, the message is there because your terminal screen is too narrow. Check this out:
https://vim.fandom.com/wiki/Avoiding_the_%22Hit_ENTER_to_continue%22_prompts

It was happening to me too. So if you open up vim in a wider terminal emulator, you won't get the error. If vim rooter could check the terminal width (:columns) and truncate the message before it displays, I'm guessing the problem would be fixed. I couldn't figure out a way to get "shortmes" to truncate the rooter message for me.

**Comment by sanga** [comment]
Truncation would probably be nicer but to be honest I would just consider not printing that message. Changing the root dir should be kinda expected behaviour for a plugin that changes the root dir ;) I don't think one would necessarily need a warning per se.

**Comment by airblade** [comment]
@sanga @kkew3 Does this only happen when the message wraps onto a second line?  Or does it always happen?

> a hint pointing to that option in the message should be of great help.

Doing something like `[vim-rooter] cwd: /path/to/root` or `cwd: $CWD (please set rooter_silent_chdir to disable this message)` would make the message longer and the hit-enter prompt more likely to occur ;)

> Changing the root dir should be kinda expected behaviour for a plugin that changes the root dir ;)

I understand your point.  The intention is that the plugin unobtrusively (i.e. without the hit-enter prompt) lets you know it's changed the directory – a message which you can ignore if you want to.

**Comment by sanga** [comment]
Sorry, for sitting on this for so long. I retested just now and it appears to be fixed i.e. I removed `rooter_silent_chdir` to get the message and it didn't require an extra enter. Neither with a large terminal window nor resized such that the "changed dir to..." message wrapped over 2 lines. I think you can close this, at least from my perspective. I'd guess this was somehow related to neovim version as I'm running a much newer version now
